package com.optimus.music.player.onix.CrazyDataStore;

/**
 * Created by apricot on 24/4/16.
 */
public class Artists {

    public static String[] artists = new String[] {

            "adele",
            "justin bieber",
            "the weeknd",
            "drake",
            "coldplay",
            "pentatonix",
            "selena golmez",
            "g-eazy",
            "taylor swift",
            "one direction",
            "fetty wap",
            "future",
            "shawn mendes",
            "jordan smith",
            "meghan trainor",
            "ellie goulding",
            "bryson tiller",
            "michael buble",
            "alessia cara",
            "twenty one pilots",
            "demi lovato",
            "ariana grande",
            "sam hunt",
            "thomas rhett",
            "elle king",
            "ed sheeran",
            "luke bryan",
            "j. cole",
            "rick ross",
            "troye sivan",
            "trans siberian orchestra",
            "stone temple pilots",
            "chris stapleton",
            "blake shelton",
            "mariah carey",
            "rachel platten",
            "elvis presley",
            "fall out boy",
            "carrie underwood",
            "travis scott",
            "frank sinatra",
            "bing crosby",
            "chris tomlin",
            "post malone",
            "nicki minaj",
            "flo rida",
            "jeremih",
            "eric church",
            "josh groban",
            "big sean",
            "john legend",
            "mannheim steamroller",
            "kendrick lamar",
            "wiz khalifa",
            "charlie puth",
            "sia",
            "chris young",
            "tory lanez",
            "x ambassadors",
            "eminem",
            "gwen stefani",
            "florida georgia line",
            "cam",
            "maroon 5",
            "andy williams",
            "daya",
            "silento",
            "5 seconds of summer",
            "rae sremmurd",
            "burl ives",
            "andy grammer",
            "jason aldean",
            "zac brown band",
            "katy perry",
            "the chainsmokers",
            "amy grant",
            "dj snake",
            "amy vachal",
            "nat king cole",
            "walk the moon",
            "andrea bocelli",
            "jeffery austin",
            "rianna",
            "vince guaraldi trio",
            "jason derulo",
            "r. city",
            "madi davis",
            "bruce springsteen",
            "brenda lee",
            "emily ann roberts",
            "hozier",
            "tim mcgraw",
            "gene autry",
            "imagine dragons",
            "young thug",
            "keith urban",
            "halsey",
            "silento",
            "kidz bop kids",
            "beyonce",
            "psy",
            "barrett baber",
            "casting crowns",
            "ilovememphis",
            "bruno mars",
            "dan + shay",
            "old dominion",
            "miley cyrus",
            "nick jonas",
            "fifth harmony",
            "omi",
            "john legend",
            "fall out boy",
            "one direction",
            "major lazer",
            "luke bryan",
            "pitbull",
            "trey songz",
            "kelly clarkson",
            "george ezra",
            "kid ink",
            "jidenna",
            "kayne west",
            "ella henderson",
            "travis scott",
            "jessie j",
            "justin timberlake",
            "lil wane",
            "p!ink",
            "the lumineers",
            "lady gaga",
            "lorde",
            "philip philips",
            "will.i.am",
            "daft punk",
            "avicii",
            "lana del rey",
            "capital cities",
            "onerepublic",
            "madonna",
            "keane",
            "snow patrol",
            "onerepublic",
            "travis",
            "oasis",
            "the fray",
            "the killers",
            "james blunt",
            "radihoead",
            "muse",
            "thirteen senses",
            "u2",
            "kings of leon",
            "stereophonics",
            "the verve",
            "foster the people",
            "foo fighters",
            "noel gallagher's high flying birds",
            "blur",
            "arctic monkeys",
            "lifehouse",
            "robbie williams",
            "beady eye",
            "placebo",
            "starsailor",
            "linkin park",
            "five for fighting",
            "manic street preachers",
            "embrace",
            "the kooks",
            "franz ferdinand",
            "r.e.m",
            "kaiser chiefs",
            "athlete",
            "richard ashcroft",
            "two door cinema club",
            "train",
            "feeder",
            "switchfoot",
            "doves",
            "suede",
            "30 seconds to mars",
            "red ot chili peppers",
            "goo goo dolls",
            "bastille",
            "pulp",
            "matchbox twenty",
            "biffy clyro",
            "brandon flowers",
            "remy zero",
            "kasablan",
            "paramore",
            "garbage",
            "semisonic",
            "neon trees",
            "editors",
            "counting crows",
            "weezer",
            "the stone roses",
            "the xx",
            "the lighting seeds",
            "the temper trap",
            "florence + the machine",
            "the cranberries",
            "new radicals",
            "jet",
            "third eye blind",
            "arcade fire",
            "angels & airwaves",
            "gorillaz",
            "mutemath",
            "mika",
            "blue october",
            "vertical horizon",
            "noel gallagher",
            "damon albarn",
            "the white stripes",
            "incubus",
            "panic! at the disco",
            "reamonn",
            "poets of the fall",
            "the smashing pumpkins",
            "morrissey",
            "the calling",
            "the wombats",
            "the raconteurs",
            "fool's garden",
            "take that",
            "jimmy eat world",
            "the resmus",
            "3 doors down",
            "nickelback",
            "anberlin",
            "ok go",
            "alanis morissette",
            "civil twilight",
            "the last goodnight",
            "the strokes",
            "bloc party",
            "creed",
            "the last shadow puppets",
            "carolina liar",
            "the vines",
            "death cab for cutie",
            "hard-fi",
            "audioslave",
            "animal jazz",
            "ghosts",
            "saybia",
            "daugtry",
            "beck",
            "breaking benjamin",
            "mat kearney",
            "fun.",
            "three days grace",
            "mew",
            "razorlight",
            "black lab",
            "augustana",
            "te all-american rejects",
            "bombay bicycle club",
            "mgmt",
            "hoobastank",
            "zoe",
            "rob thomas",
            "lostpropets",
            "dead by sunrise",
            "the bravery",
            "lenny kravitz",
            "cage the elephant",
            "black rebel motorcycle club",
            "the 1975",
            "alt-j",
            "dave matthews band",
            "the boxer rebellion",
            "myslovitz",
            "the fratellis",
            "staind",
            "echosmith",
            "boyce avenue",
            "aqualung",
            "young the giant",
            "new politics",
            "wite lies",
            "urt",
            "collective soul",
            "the national",
            "safetysuit",
            "plain white t's",
            "no doubt",
            "chris cornel",
            "sunrise avenue",
            "hot celle rae",
            "lilly allen",
            "boys like girls",
            "ima robot",
            "rage against the macine",
            "my chemical romance",
            "green day",
            "yeah yeah yeahs",
            "the pretty reckless",
            "evermore",
            "cobra starship",
            "awolnation",
            "thom yorke",
            "foals",
            "the cardigans",
            "secondhand serenade",
            "thriving ivory",
            "alex turner",
            "miles kane",
            "the libertines",
            "david cook",
            "the feeling",
            "mumm-ra",
            "babyshambles",
            "a perfect circle",
            "interpol",
            "one night only",
            "dashboard confessional",
            "the hoosiers",
            "blush",
            "skylar grey",
            "the academy is...",
            "birds of tokyo",
            "mkto",
            "billy talent",
            "lighthouse family",
            "alter bridge",
            "lilly joy",
            "broken bells",
            "the subways",
            "woodkid",
            "glasvegas",
            "crosses",
            "melee",
            "nada surf",
            "mcfly",
            "sleeping at last",
            "carpark north",
            "papa roach",
            "turin brakes",
            "silversun pickups",
            "royal blood",
            "tired pony",
            "sixpence none the richer",
            "eddie vedder",
            "spector",
            "the pershers",
            "american authors",
            "gavin degraw",
            "jay-z and linkin park",
            "pearl jam",
            "sting",
            "clean bandit",
            "howie day",
            "happysad",
            "badly drawn boy",
            "copeland",
            "mikky ekko",
            "crowded house",
            "ms mr",
            "serj tankian",
            "kongos",
            "the neighbourhood",
            "gotye",
            "dave gahan",
            "julian casablancas",
            "will young",
            "silverchair",
            "kashmir",
            "the afters",
            "eskimo joe",
            "morning parade",
            "tiago lorc",
            "a silent film",
            "gerard way",
            "fran healy",
            "on-the-go",
            "arthur rojek",
            "kensington",
            "rpa & the united nations of sound",
            "chris martin",
            "andra and the backbone",
            "neon jungle",
            "rihanna"

    };
}
