package com.optimus.music.player.onix.CrazyDataStore;

/**
 * Created by apricot on 15/11/15.
 */
public class ArtistNames {

    public static String[] artistNames = new String[]{
            //Bollywood
            "armaan mallik",
            "amal mallik",
            "tony kakkar",
            "mithoon",
            "meet bros",
            "benny dayal",
            "nucleya",
            "arjun kanungo",
            "amit trivedi",
            "sonu kakkar",

            "pandit jasraj",
            "sonu nigam",
            "udit narayan",
            "alka yagnik",
            "shaan",
            "arijit singh",
            "shreya ghoshal",
            "sunidhi chauhan",
            "kumar sanu",
            "k k",
            "k. k.",
            "mohit chauhan",
            "kailash kher",
            "asha bhosle",
            "lata mangeshkar",
            "kavita krishnamurthy",
            "honey singh",
            "himesh reshammiya",
            "a. r. rahman",
            "a r rahman",
            "ar rahman",
            "mika singh",
            "zubeen garg",
            "neha kakkar",
            "parthiv gohil",
            "shankar mahadevan",
            "hariharan",
            "abhijeet",
            "chinmayi",
            "sukhwinder singh",
            "mahalakshmi iyer",
            "lucky ali",
            "rekha bhardwaj",
            "neeraj shridhar",
            "pritam",
            "javed ali",
            "adnan sami",
            "rahat fateh ali khan",
            "shafqat amanat ali",
            "neha bhasin",
            "vishal dadlani",
            "richa sharma",
            "ustad rashid khan",
            "tochi raina",
            "monali thakur",
            "kavita seth",
            "rahul vaidya",
            "ankit tiwari",
            "atif aslam",
            "ali zafar",
            "amit trivedi",


            //bengali
            "indranil sen",
            "indrani sen",
            "rupankar",
            "rupankar bagchi",
            "sraboni sen",
            "somlata acharya",
            "anupam roy",
            "arnob",
            "srikanta acharya",
            "antara chowdhury",
            "nachiketa chakraborty",
            "nachiketa",

            "kanika kapoor",
            "babul supriyo",
            "chitra singh",
            "sahana bajpayee",
            "divya kumar",
            "jagjit singh",
            "nusrat fateh ali",
            "shilpa rao",
            "palash sen",
            "sadhana sargam",
            "saptarshi mukherjee",
            "shantanu moitra",
            "shail hada",
            "soham",
            "swadanand kirkire",
            "toshi sabri",
            "ujjaini mukherjee",
            "armaan malik",
            "alisha chinoy",
            "chitra singh",
            "sadhana sargam",
            "vasundhara das",
            "kamal khan",
            "labh janjua",
            "naresh iyer",
            "suzanne d'mello",
            "pandit birju maharaj",
            "payal dev",
            "dominique cerejo",
            "raman mahadevan",
            "roop kumar rathod"

    };

}
